# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8039d4e64e58d50cc7e1add80eecdf39885383b0d98bb9b19e954e45e2c8bae9f620ec667209bba3169abb8768c87650ae4fef573d0faff64a2950bf33b7c6f0

test:
  secret_key_base: f592ccc088216bfcaef601dcc443ace9150def0770a69f1153ec80d8b468ee9be30690fe053be146eb23608595537f5fc80d93a1e4a1aaee70be198fd74a8a03

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
